version: '3.6'
services:
  francisjgarcia:
    container_name: francisjgarcia
    image: httpd
    ports:
        - ${WEB_EXPOSE_PORT}:80
    volumes:
        - ../public:/usr/local/apache2/htdocs
    restart: always
