version: '3.8'
services:
  francisjgarcia.es:
    container_name: francisjgarcia.es
    image: francisjgarcia/francisjgarcia.es
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
        - ${WEB_EXPOSE_PORT}:80
    volumes:
        - ../public:/usr/share/nginx/html
    deploy:
      resources:
        limits:
          memory: 10M
        reservations:
          memory: 6M
    restart: always
